databases:
  - name: queso_sistemadb
    plan: free
    databaseName: queso_sistema
    user: queso_sistema

services:
  - type: web
    plan: free
    name: queso_sistema
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn queso_sistema.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: queso_sistemadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4